# Default values for jenkins-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
#imagePullSecrets:
image:
#  repository: mydevopsacr001.azurecr.io/jenkins-cicd
  repository: ccr.ccs.tencentyun.com/my-registry/jenkins
  tag: lts-k8s
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
  agentPort: 50000

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
